// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ZepterTask.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250117205746_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZepterTask.Models.Domain.CustomerAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("CustomerAddresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "City 1",
                            OrderId = 1,
                            PostalCode = "00-01",
                            Street = "Street 1"
                        },
                        new
                        {
                            Id = 2,
                            City = "City 2",
                            OrderId = 2,
                            PostalCode = "00-02",
                            Street = "Street 2"
                        },
                        new
                        {
                            Id = 3,
                            City = "City 3",
                            OrderId = 3,
                            PostalCode = "00-03",
                            Street = "Street 3"
                        },
                        new
                        {
                            Id = 4,
                            City = "City 4",
                            OrderId = 4,
                            PostalCode = "00-04",
                            Street = "Street 4"
                        },
                        new
                        {
                            Id = 5,
                            City = "City 5",
                            OrderId = 5,
                            PostalCode = "00-05",
                            Street = "Street 5"
                        },
                        new
                        {
                            Id = 6,
                            City = "City 6",
                            OrderId = 6,
                            PostalCode = "00-06",
                            Street = "Street 6"
                        },
                        new
                        {
                            Id = 7,
                            City = "City 7",
                            OrderId = 7,
                            PostalCode = "00-07",
                            Street = "Street 7"
                        },
                        new
                        {
                            Id = 8,
                            City = "City 8",
                            OrderId = 8,
                            PostalCode = "00-08",
                            Street = "Street 8"
                        },
                        new
                        {
                            Id = 9,
                            City = "City 9",
                            OrderId = 9,
                            PostalCode = "00-09",
                            Street = "Street 9"
                        },
                        new
                        {
                            Id = 10,
                            City = "City 10",
                            OrderId = 10,
                            PostalCode = "00-010",
                            Street = "Street 10"
                        },
                        new
                        {
                            Id = 11,
                            City = "City 11",
                            OrderId = 11,
                            PostalCode = "00-011",
                            Street = "Street 11"
                        },
                        new
                        {
                            Id = 12,
                            City = "City 12",
                            OrderId = 12,
                            PostalCode = "00-012",
                            Street = "Street 12"
                        },
                        new
                        {
                            Id = 13,
                            City = "City 13",
                            OrderId = 13,
                            PostalCode = "00-013",
                            Street = "Street 13"
                        },
                        new
                        {
                            Id = 14,
                            City = "City 14",
                            OrderId = 14,
                            PostalCode = "00-014",
                            Street = "Street 14"
                        },
                        new
                        {
                            Id = 15,
                            City = "City 15",
                            OrderId = 15,
                            PostalCode = "00-015",
                            Street = "Street 15"
                        },
                        new
                        {
                            Id = 16,
                            City = "City 16",
                            OrderId = 16,
                            PostalCode = "00-016",
                            Street = "Street 16"
                        },
                        new
                        {
                            Id = 17,
                            City = "City 17",
                            OrderId = 17,
                            PostalCode = "00-017",
                            Street = "Street 17"
                        },
                        new
                        {
                            Id = 18,
                            City = "City 18",
                            OrderId = 18,
                            PostalCode = "00-018",
                            Street = "Street 18"
                        },
                        new
                        {
                            Id = 19,
                            City = "City 19",
                            OrderId = 19,
                            PostalCode = "00-019",
                            Street = "Street 19"
                        },
                        new
                        {
                            Id = 20,
                            City = "City 20",
                            OrderId = 20,
                            PostalCode = "00-020",
                            Street = "Street 20"
                        },
                        new
                        {
                            Id = 21,
                            City = "City 21",
                            OrderId = 21,
                            PostalCode = "00-021",
                            Street = "Street 21"
                        },
                        new
                        {
                            Id = 22,
                            City = "City 22",
                            OrderId = 22,
                            PostalCode = "00-022",
                            Street = "Street 22"
                        },
                        new
                        {
                            Id = 23,
                            City = "City 23",
                            OrderId = 23,
                            PostalCode = "00-023",
                            Street = "Street 23"
                        },
                        new
                        {
                            Id = 24,
                            City = "City 24",
                            OrderId = 24,
                            PostalCode = "00-024",
                            Street = "Street 24"
                        },
                        new
                        {
                            Id = 25,
                            City = "City 25",
                            OrderId = 25,
                            PostalCode = "00-025",
                            Street = "Street 25"
                        },
                        new
                        {
                            Id = 26,
                            City = "City 26",
                            OrderId = 26,
                            PostalCode = "00-026",
                            Street = "Street 26"
                        },
                        new
                        {
                            Id = 27,
                            City = "City 27",
                            OrderId = 27,
                            PostalCode = "00-027",
                            Street = "Street 27"
                        },
                        new
                        {
                            Id = 28,
                            City = "City 28",
                            OrderId = 28,
                            PostalCode = "00-028",
                            Street = "Street 28"
                        },
                        new
                        {
                            Id = 29,
                            City = "City 29",
                            OrderId = 29,
                            PostalCode = "00-029",
                            Street = "Street 29"
                        },
                        new
                        {
                            Id = 30,
                            City = "City 30",
                            OrderId = 30,
                            PostalCode = "00-030",
                            Street = "Street 30"
                        });
                });

            modelBuilder.Entity("ZepterTask.Models.Domain.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PaymentMethod = 1,
                            StoreId = 2
                        },
                        new
                        {
                            Id = 2,
                            PaymentMethod = 2,
                            StoreId = 3
                        },
                        new
                        {
                            Id = 3,
                            PaymentMethod = 0,
                            StoreId = 4
                        },
                        new
                        {
                            Id = 4,
                            PaymentMethod = 1,
                            StoreId = 5
                        },
                        new
                        {
                            Id = 5,
                            PaymentMethod = 2,
                            StoreId = 6
                        },
                        new
                        {
                            Id = 6,
                            PaymentMethod = 0,
                            StoreId = 7
                        },
                        new
                        {
                            Id = 7,
                            PaymentMethod = 1,
                            StoreId = 8
                        },
                        new
                        {
                            Id = 8,
                            PaymentMethod = 2,
                            StoreId = 9
                        },
                        new
                        {
                            Id = 9,
                            PaymentMethod = 0,
                            StoreId = 10
                        },
                        new
                        {
                            Id = 10,
                            PaymentMethod = 1,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 11,
                            PaymentMethod = 2,
                            StoreId = 2
                        },
                        new
                        {
                            Id = 12,
                            PaymentMethod = 0,
                            StoreId = 3
                        },
                        new
                        {
                            Id = 13,
                            PaymentMethod = 1,
                            StoreId = 4
                        },
                        new
                        {
                            Id = 14,
                            PaymentMethod = 2,
                            StoreId = 5
                        },
                        new
                        {
                            Id = 15,
                            PaymentMethod = 0,
                            StoreId = 6
                        },
                        new
                        {
                            Id = 16,
                            PaymentMethod = 1,
                            StoreId = 7
                        },
                        new
                        {
                            Id = 17,
                            PaymentMethod = 2,
                            StoreId = 8
                        },
                        new
                        {
                            Id = 18,
                            PaymentMethod = 0,
                            StoreId = 9
                        },
                        new
                        {
                            Id = 19,
                            PaymentMethod = 1,
                            StoreId = 10
                        },
                        new
                        {
                            Id = 20,
                            PaymentMethod = 2,
                            StoreId = 1
                        },
                        new
                        {
                            Id = 21,
                            PaymentMethod = 0,
                            StoreId = 2
                        },
                        new
                        {
                            Id = 22,
                            PaymentMethod = 1,
                            StoreId = 3
                        },
                        new
                        {
                            Id = 23,
                            PaymentMethod = 2,
                            StoreId = 4
                        },
                        new
                        {
                            Id = 24,
                            PaymentMethod = 0,
                            StoreId = 5
                        },
                        new
                        {
                            Id = 25,
                            PaymentMethod = 1,
                            StoreId = 6
                        },
                        new
                        {
                            Id = 26,
                            PaymentMethod = 2,
                            StoreId = 7
                        },
                        new
                        {
                            Id = 27,
                            PaymentMethod = 0,
                            StoreId = 8
                        },
                        new
                        {
                            Id = 28,
                            PaymentMethod = 1,
                            StoreId = 9
                        },
                        new
                        {
                            Id = 29,
                            PaymentMethod = 2,
                            StoreId = 10
                        },
                        new
                        {
                            Id = 30,
                            PaymentMethod = 0,
                            StoreId = 1
                        });
                });

            modelBuilder.Entity("ZepterTask.Models.Domain.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("GrossPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GrossPrice = 121m,
                            NetPrice = 101m,
                            OrderId = 1,
                            ProductCode = "P1",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            GrossPrice = 122m,
                            NetPrice = 102m,
                            OrderId = 2,
                            ProductCode = "P2",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            GrossPrice = 123m,
                            NetPrice = 103m,
                            OrderId = 3,
                            ProductCode = "P3",
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4,
                            GrossPrice = 124m,
                            NetPrice = 104m,
                            OrderId = 4,
                            ProductCode = "P4",
                            Quantity = 4
                        },
                        new
                        {
                            Id = 5,
                            GrossPrice = 125m,
                            NetPrice = 105m,
                            OrderId = 5,
                            ProductCode = "P5",
                            Quantity = 5
                        },
                        new
                        {
                            Id = 6,
                            GrossPrice = 126m,
                            NetPrice = 106m,
                            OrderId = 6,
                            ProductCode = "P6",
                            Quantity = 6
                        },
                        new
                        {
                            Id = 7,
                            GrossPrice = 127m,
                            NetPrice = 107m,
                            OrderId = 7,
                            ProductCode = "P7",
                            Quantity = 7
                        },
                        new
                        {
                            Id = 8,
                            GrossPrice = 128m,
                            NetPrice = 108m,
                            OrderId = 8,
                            ProductCode = "P8",
                            Quantity = 8
                        },
                        new
                        {
                            Id = 9,
                            GrossPrice = 129m,
                            NetPrice = 109m,
                            OrderId = 9,
                            ProductCode = "P9",
                            Quantity = 9
                        },
                        new
                        {
                            Id = 10,
                            GrossPrice = 130m,
                            NetPrice = 110m,
                            OrderId = 10,
                            ProductCode = "P10",
                            Quantity = 10
                        },
                        new
                        {
                            Id = 11,
                            GrossPrice = 131m,
                            NetPrice = 111m,
                            OrderId = 11,
                            ProductCode = "P11",
                            Quantity = 11
                        },
                        new
                        {
                            Id = 12,
                            GrossPrice = 132m,
                            NetPrice = 112m,
                            OrderId = 12,
                            ProductCode = "P12",
                            Quantity = 12
                        },
                        new
                        {
                            Id = 13,
                            GrossPrice = 133m,
                            NetPrice = 113m,
                            OrderId = 13,
                            ProductCode = "P13",
                            Quantity = 13
                        },
                        new
                        {
                            Id = 14,
                            GrossPrice = 134m,
                            NetPrice = 114m,
                            OrderId = 14,
                            ProductCode = "P14",
                            Quantity = 14
                        },
                        new
                        {
                            Id = 15,
                            GrossPrice = 135m,
                            NetPrice = 115m,
                            OrderId = 15,
                            ProductCode = "P15",
                            Quantity = 15
                        },
                        new
                        {
                            Id = 16,
                            GrossPrice = 136m,
                            NetPrice = 116m,
                            OrderId = 16,
                            ProductCode = "P16",
                            Quantity = 16
                        },
                        new
                        {
                            Id = 17,
                            GrossPrice = 137m,
                            NetPrice = 117m,
                            OrderId = 17,
                            ProductCode = "P17",
                            Quantity = 17
                        },
                        new
                        {
                            Id = 18,
                            GrossPrice = 138m,
                            NetPrice = 118m,
                            OrderId = 18,
                            ProductCode = "P18",
                            Quantity = 18
                        },
                        new
                        {
                            Id = 19,
                            GrossPrice = 139m,
                            NetPrice = 119m,
                            OrderId = 19,
                            ProductCode = "P19",
                            Quantity = 19
                        },
                        new
                        {
                            Id = 20,
                            GrossPrice = 140m,
                            NetPrice = 120m,
                            OrderId = 20,
                            ProductCode = "P20",
                            Quantity = 20
                        },
                        new
                        {
                            Id = 21,
                            GrossPrice = 141m,
                            NetPrice = 121m,
                            OrderId = 21,
                            ProductCode = "P21",
                            Quantity = 21
                        },
                        new
                        {
                            Id = 22,
                            GrossPrice = 142m,
                            NetPrice = 122m,
                            OrderId = 22,
                            ProductCode = "P22",
                            Quantity = 22
                        },
                        new
                        {
                            Id = 23,
                            GrossPrice = 143m,
                            NetPrice = 123m,
                            OrderId = 23,
                            ProductCode = "P23",
                            Quantity = 23
                        },
                        new
                        {
                            Id = 24,
                            GrossPrice = 144m,
                            NetPrice = 124m,
                            OrderId = 24,
                            ProductCode = "P24",
                            Quantity = 24
                        },
                        new
                        {
                            Id = 25,
                            GrossPrice = 145m,
                            NetPrice = 125m,
                            OrderId = 25,
                            ProductCode = "P25",
                            Quantity = 25
                        },
                        new
                        {
                            Id = 26,
                            GrossPrice = 146m,
                            NetPrice = 126m,
                            OrderId = 26,
                            ProductCode = "P26",
                            Quantity = 26
                        },
                        new
                        {
                            Id = 27,
                            GrossPrice = 147m,
                            NetPrice = 127m,
                            OrderId = 27,
                            ProductCode = "P27",
                            Quantity = 27
                        },
                        new
                        {
                            Id = 28,
                            GrossPrice = 148m,
                            NetPrice = 128m,
                            OrderId = 28,
                            ProductCode = "P28",
                            Quantity = 28
                        },
                        new
                        {
                            Id = 29,
                            GrossPrice = 149m,
                            NetPrice = 129m,
                            OrderId = 29,
                            ProductCode = "P29",
                            Quantity = 29
                        },
                        new
                        {
                            Id = 30,
                            GrossPrice = 150m,
                            NetPrice = 130m,
                            OrderId = 30,
                            ProductCode = "P30",
                            Quantity = 30
                        });
                });

            modelBuilder.Entity("ZepterTask.Models.Domain.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sklep 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sklep 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sklep 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sklep 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sklep 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sklep 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Sklep 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Sklep 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Sklep 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Sklep 10"
                        });
                });

            modelBuilder.Entity("ZepterTask.Models.Domain.CustomerAddress", b =>
                {
                    b.HasOne("ZepterTask.Models.Domain.Order", "Order")
                        .WithOne("CustomerAddress")
                        .HasForeignKey("ZepterTask.Models.Domain.CustomerAddress", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ZepterTask.Models.Domain.Order", b =>
                {
                    b.HasOne("ZepterTask.Models.Domain.Store", "Store")
                        .WithMany("Orders")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ZepterTask.Models.Domain.OrderLine", b =>
                {
                    b.HasOne("ZepterTask.Models.Domain.Order", "Order")
                        .WithMany("OrderLines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ZepterTask.Models.Domain.Order", b =>
                {
                    b.Navigation("CustomerAddress")
                        .IsRequired();

                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("ZepterTask.Models.Domain.Store", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
